In [1]:
from scipy.stats import f
import numpy as np

In [2]:
data = np.array([[58, 64, 55, 66, 67], [58, 69, 71, 64, 68], [48, 57, 59, 47, 49]])
data

array([[58, 64, 55, 66, 67],
       [58, 69, 71, 64, 68],
       [48, 57, 59, 47, 49]])

In [3]:
sample_size = [len(x) for x in data]
sample_size

[5, 5, 5]

In [4]:
n = sum(sample_size)
k = len(sample_size)
print n, k

15 3


In [5]:
grand_mean = data.mean()
print grand_mean

60.0


In [6]:
sample_mean = data.mean(axis =1)
print sample_mean

[ 62.  66.  52.]


In [7]:
s = data.std(axis=1, ddof=1)
print s

[ 5.24404424  5.14781507  5.56776436]


In [8]:
zip(sample_size, sample_mean)

[(5, 62.0), (5, 66.0), (5, 52.0)]

In [9]:
# Compute SSTR (sum of squares due to or between treatments) 
# While computing SSTR, we ignore the variations within treatment
# Thus, it is as if each number were replaced with the sample mean of its treatment or group.

SSTR = sum([x*(y-grand_mean)**2 for x, y in zip(sample_size, sample_mean)])
df_tr = k - 1
MSTR = SSTR/df_tr
print SSTR, MSTR

520.0 260.0


In [10]:
# Compute SSE (sum of squares due to error within treatment)

SSE = sum([(x-1)*(y**2) for x, y in zip(sample_size, s)])
df_e = n - k
MSE = SSE/df_e

print SSE, MSE

340.0 28.3333333333


In [11]:
# Compte SST (sum of squared total variation)

SST = (n-1)*data.std(ddof=1)**2
df_t = n - 1
print SST, SSTR+SSE

860.0 860.0


In [14]:
# ANOVA: f test

f_stat = MSTR/MSE
crit = f.ppf(.95, dfn=df_tr, dfd=df_e)
p_value = 1 - f.cdf(f_stat, dfn=df_tr, dfd=df_e)

print crit
print
print 'treatment  ', SSTR, '    ', df_tr, '    ', MSTR, '    ', f_stat, '    ', p_value
print 'error      ', SSE, '    ', df_e, '   ', MSE
print 'total      ', SST, '    ', df_t

3.88529383465

treatment   520.0      2      260.0      9.17647058824      0.00381841207551
error       340.0      12     28.3333333333
total       860.0      14
