In [1]:
from scipy.stats import f
import numpy as np

In [2]:
data = np.array([[[500, 580], [540, 460], [480, 400]], 
                 [[460, 540], [560, 620], [420, 480]], 
                 [[560, 600], [600, 580], [480, 410]]])

# Compute overall sample mean
grand_mean = data.mean()

# Compte factor A means
A_mean = data.mean(axis=(2, 1))

# Compte factor B means
B_mean = data.mean(axis=(2, 0))

# Compte each of the 9 treatment means
TR_mean = data.mean(axis=2)

In [3]:
data.mean(axis=2)

array([[ 540.,  500.,  440.],
       [ 500.,  590.,  450.],
       [ 580.,  590.,  445.]])

In [4]:
data.mean(axis=(2, 1))

array([ 493.33333333,  513.33333333,  538.33333333])

In [5]:
data.mean(axis=(2, 0))

array([ 540.,  560.,  445.])

In [6]:
SST = sum([(x-grand_mean)**2. for x in data.flatten()])

In [7]:
# flatten a numpy array
data.flatten()

array([500, 580, 540, 460, 480, 400, 460, 540, 560, 620, 420, 480, 560,
       600, 600, 580, 480, 410])

In [8]:
# shape of numpy array
data.shape

(3L, 3L, 2L)

##### (3, 3, 2) = (a, b, r)
We thus have the number of levels of factor A, the number of levels of factor B, and number of replications in each treatment

In [9]:
a = data.shape[0]; b = data.shape[1]; r = data.shape[2]

In [10]:
SSA = b*r*sum([(x-grand_mean)**2. for x in A_mean])

In [11]:
SSB = a*r*sum([(x-grand_mean)**2. for x in B_mean])

In [12]:
# Compute SSAB
SSAB = 0
for i in range(a):
    for j in range(b):
        SSAB += (TR_mean[i][j] - A_mean[i] - B_mean[j] + grand_mean)**2.
SSAB = r*SSAB

In [13]:
# Compute SSE
SSE = SST - SSA - SSB - SSAB

In [14]:
# degrees of freedom
dfa = data.shape[0] - 1
dfb = data.shape[1] - 1
dfab = dfa*dfb
dfe = data.shape[0]*data.shape[1]*(data.shape[2]-1)
dft = data.shape[0]*data.shape[1]*data.shape[2]-1

In [15]:
# Mean Squares
MSA = SSA/dfa
MSB = SSB/dfb
MSAB = SSAB/dfab
MSE = SSE/dfe

In [16]:
# F test statistics
fa = MSA/MSE
fb = MSB/MSE
fab = MSAB/MSE

In [17]:
# p-values
pa = 1 - f.cdf(fa, dfn=dfa, dfd=dfe)
pb = 1 - f.cdf(fb, dfn=dfb, dfd=dfe)
pab = 1 - f.cdf(fab, dfn=dfab, dfd=dfe)

In [18]:
print 'Factor A', '    ', SSA, '    ', dfa, '    ', MSA, '    ', fa, '    ', pa
print 'Factor B', '    ', SSB, '   ', dfb, '    ', MSB, '   ', fb, '    ', pb
print 'Interaction', ' ', SSAB, '   ', dfab, '    ', MSAB, '    ', fab, '    ', pab
print 'Error', '       ', SSE, '   ', dfe, '    ', MSE
print 'Total', '       ', SST, '   ', dft

Factor A      6100.0      2      3050.0      1.38287153652      0.299436108572
Factor B      45300.0     2      22650.0     10.2695214106      0.00475671804937
Interaction   11200.0     4      2800.0      1.26952141058      0.350327769325
Error         19850.0     9      2205.55555556
Total         82450.0     17
